export const BROADCAST_ACTIONS = {
	SUCCESS_DISCORD_AUTH: "SUCCESS_DISCORD_AUTH",
	FAILURE_DISCORD_AUTH: "FAILURE_DISCORD_AUTH",
	SUCCESS_TWITTER_AUTH: "SUCCESS_TWITTER_AUTH",
	UPDATE_BILLING_INFO: "UPDATE_BILLING_INFO",
	SUCCESS_USER_LOGIN: "SUCCESS_USER_LOGIN",
	UPDATE_INTEGRATIONS: "UPDATE_INTEGRATIONS",
}
