export const ERROR_CODE = {
  DISCORD_ACCOUNT_ALREADY_REGISTERED: "DISCORD_ACCOUNT_ALREADY_REGISTERED",
  DISCORD_NOT_CONNECTED: "DISCORD_NOT_CONNECTED",
  SUBSCRIPTION_EXISTS: "SUBSCRIPTION_EXISTS",
}
