export const categories = [
  {
    id: "1",
    name: "Lead Gen",
    templates: [
      {
        id: "1",
        name: "Grow my Twitter",
        type: "Following",
        description: "description",
        imgSrc: "",
      },
      {
        id: "2",
        name: "Download Video",
        type: "Download",
        imgSrc: "",
        description: "description",
      },
      {
        id: "3",
        name: "Upload Video",
        type: "Upload",
        imgSrc: "",
        description: "description",
      },
      {
        id: "4",
        name: "Grow my Twitter",
        type: "Following",
        imgSrc: "",
        description: "description",
      },
      {
        id: "5",
        name: "Grow my Twitter",
        type: "Following",
        imgSrc: "",
        description: "description",
      },
      {
        id: "6",
        name: "Grow my Twitter",
        type: "Following",
        imgSrc: "",
        description: "description",
      },
      {
        id: "7",
        name: "Grow my Twitter",
        type: "Following",
        imgSrc: "",
        description: "description",
      },
      {
        id: "8",
        name: "Grow my Twitter",
        type: "Following",
        imgSrc: "",
        description: "description",
      },
    ],
  },
  {
    id: "2",
    name: "Lead Gen 2",
    templates: [
      {
        id: "9",
        name: "Grow my Twitter Grow my Twitter Grow my Twitter",
        type: "Following Following FollowingFollowing",
        imgSrc: "",
        description: "description description description description",
      },
      {
        id: "10",
        name: "Upload video",
        type: "Following",
        imgSrc: "",
        description: "description",
      },
      {
        id: "11",
        name: "Grow my Twitter",
        type: "Following",
        imgSrc: "",
        description: "description",
      },
      {
        id: "12",
        name: "Grow my Twitter",
        type: "Following",
        imgSrc: "",
        description: "description",
      },
      {
        id: "13",
        name: "Grow my Twitter",
        type: "Following",
        imgSrc: "",
        description: "description",
      },
    ],
  },
  {
    id: "3",
    name: "Lead Gen 3",
    templates: [
    ],
  },
];
