import {Activity} from "../../Types/QuestTypes";

const emptyFunction = () => {};

const defaultOnboadingAnimationState = {
	spaceLoading: false,
	headerLoading: false,
	socialLoading: false,
	descriptionLoading: false,
	campaignLoading: false,
	perkLoading: false,
	success: false,
};

export const DEFAULT_BUILDER = {
	openFloSpace: false,
	openDesignPanel: false,
	openFloAddModal: false,
	openPerkAddModal: false,
	activityLoading: false,
	headerState: {
		title: "",
		description: "",
		header_button_text: "",
		isChanged: false,
		showDescription: true,
		showPageStatistics: true,
		showSocialLinks: true,
		showButton: true,
		main_campaign_id: null,
		end_button_text: "",
	},
	editorState: {
		campaign_name: "",
		campaign_description: "",
		isChanged: false,
		campaign: null,
		endTitle: "",
		endDescription: "",
		showEndSocialLinks: true,
		showEndDescription: true,
		showDescription: true,
		terms_and_conditions: "",
		end_button_text: "",
		end_campaign_id: null,
		end_website: null,
		endImageFile: null,
		end_page_type: "",
		perksToDisplay: [],
		imageFile: null,
	},
	conditionToEdit: null,
	modules: null,
	activityEditingState: {
		activity_id: "",
		name: "",
		description: "",
		isChangesToSave: false,
		showSecondaryImage: false,
		text_content: "",
		points: 0,
		secondaryImageFile: null,
		activity_url: null,
		file: null,
		image_tint_color: null,
	},
	activity:null,
	questionEditingState: {
		question: null,
		multipleSelection: false,
		isChangesToSave: false,
		options: ["Option A...", "Option B..."],
		answers: [0],
		showOther: false,
	},
	perks: [],
	onboardingState: defaultOnboadingAnimationState,
	onboardingLoadingMessg: "",
	combineOnboardingLoading: false,
	setOpenFloSpace: emptyFunction,
	setOpenDesignPanel: emptyFunction,
	setFloThemes: emptyFunction,
	updateFloThemeData: emptyFunction,
	setActiveTheme: emptyFunction,
	setHeaderState: emptyFunction,
	setConditionToEdit: emptyFunction,
	updateCampaignToEdit: emptyFunction,
	setEditorState: emptyFunction,
	fetchActivityToEdit: emptyFunction,
	setActivityEditingState: emptyFunction,
	updateActivityModules: (campaign_id?: string) => {},
	setQuestionEditingState: emptyFunction,
	updateRewardData: emptyFunction,
	setRewardSettings: emptyFunction,
	setOnboardingState: emptyFunction,
	setOnboardingLoadingMessg: emptyFunction,
	setOnboardingLoading: emptyFunction,
	setOpenFloAddModal: emptyFunction,
	setOpenPerkAddModal: emptyFunction,
	floThemes: null,
	activeTheme: null,
	campaignLoading: false,
	autoSaveRunning: false,
	setActivity: (activity: Activity | null) => {},
};
